"""
Local XTTSv2 Emotive Speech API Plugin for JARVIS.
Connects to a running local XTTS server (port 8020 default)
and generates emotive voice files on the fly.
Supports: joy, anger, sad, whisper, excited.
"""

import os
import requests
import logging
import asyncio
from livekit.agents import tts
from livekit.agents.tts.tts import DEFAULT_API_CONNECT_OPTIONS

logger = logging.getLogger(__name__)

import glob
import time

def _cleanup_xtts_output_folder():
    """Removes leftover WAV files generated by xtts-api-server to prevent disk bloat."""
    try:
        now = time.time()
        for folder in ["output", "/tmp/xtts_output"]:
            if os.path.exists(folder):
                for f in glob.glob(os.path.join(folder, "*.wav")):
                    try:
                        if (now - os.path.getmtime(f)) > 15:  # Purge files older than 15s
                            os.remove(f)
                    except Exception:
                        pass
    except Exception as e:
        pass

class XTTSChunkedStream(tts.ChunkedStream):
    async def _run(self, output_emitter: tts.AudioEmitter) -> None:
        try:
            # We determine text structure to pick the appropriate emotion style
            text = self.input_text.lower()
            emotion = "neutral"

            if any(w in text for w in ["fatal", "error", "snag", "warning", "fail"]):
                emotion = "disappointment"  # sad/concerned
            elif any(w in text for w in ["hello", "welcome", "ready", "online", "operational"]):
                emotion = "joy"  # enthusiastic
            elif "ssh" in text or "locked" in text or "lockout" in text:
                emotion = "sad" # serious/whisper

            logger.info(f"XTTS: Synthesizing voice for '{self.input_text[:40]}...' with emotion '{emotion}'")

            # Request audio from local XTTS container/api (/tts_to_audio/ endpoint)
            url = os.getenv("XTTS_SERVER_URL", "http://localhost:8020/tts_to_audio/")
            payload = {
                "text": self.input_text,
                "language": "en",
                "speaker_wav": os.path.abspath("jarvis_memory/master_voice.wav")
            }

            # Direct POST to XTTS server API
            loop = asyncio.get_running_loop()
            resp = await loop.run_in_executor(
                None,
                lambda: requests.post(url, json=payload, timeout=20)
            )

            # Schedule automatic disk cleanup in background
            loop.run_in_executor(None, _cleanup_xtts_output_folder)


            if resp.status_code == 200:
                import io
                import wave
                audio_bytes = resp.content
                with wave.open(io.BytesIO(audio_bytes), 'rb') as wav_file:
                    sample_rate = wav_file.getframerate()
                    pcm_bytes = wav_file.readframes(wav_file.getnframes())

                output_emitter.initialize(
                    request_id="xtts_tts",
                    sample_rate=sample_rate,
                    num_channels=1,
                    mime_type="audio/pcm"
                )
                output_emitter.push(pcm_bytes)
                output_emitter.flush()
            else:
                raise RuntimeError(f"XTTS local API returned status code {resp.status_code}")

        except Exception as e:
            logger.warning(f"XTTS generation failed: {e}. Falling back to Piper...")
            try:
                if not hasattr(self._tts, "_piper_fallback") or self._tts._piper_fallback is None:
                    import piper_tts_plugin
                    self._tts._piper_fallback = piper_tts_plugin.PiperTTS()
                
                piper_stream = self._tts._piper_fallback.synthesize(self.input_text, conn_options=self._conn_options)
                await piper_stream._run(output_emitter)
            except Exception as piper_err:
                logger.error(f"Piper TTS fallback also failed: {piper_err}")
                self._emit_error(piper_err, recoverable=False)
                raise piper_err

class XTTSTTS(tts.TTS):
    def __init__(self):
        super().__init__(
            capabilities=tts.TTSCapabilities(streaming=False),
            sample_rate=24000,
            num_channels=1,
        )

    @property
    def model(self) -> str:
        return "xtts-v2-local"

    @property
    def provider(self) -> str:
        return "local-xtts"

    def synthesize(self, text: str, *, conn_options = None) -> tts.ChunkedStream:
        if conn_options is None:
            conn_options = DEFAULT_API_CONNECT_OPTIONS
        return XTTSChunkedStream(tts=self, input_text=text, conn_options=conn_options)
